"""Add name column to users

Revision ID: 66ebade295e9
Revises: 
Create Date: 2025-12-01 19:51:25.367878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66ebade295e9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('learner_profiles')
    op.drop_table('mentorship_sessions')
    op.drop_table('user_accessibility_needs')
    op.drop_table('administrator_profiles')
    op.drop_table('course_modules')
    op.drop_table('course_accessibility_features')
    op.drop_table('module_content')
    op.drop_table('mentor_profiles')
    op.alter_column('courses', 'category',
               existing_type=postgresql.ENUM('TECHNOLOGY', 'VOCATIONAL', 'SOFT_SKILLS', 'LITERACY', name='coursecategory'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('courses', 'difficulty',
               existing_type=postgresql.ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='coursedifficulty'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('LEARNER', 'MENTOR', 'ADMINISTRATOR', name='userrole'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('users', 'role',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('LEARNER', 'MENTOR', 'ADMINISTRATOR', name='userrole'),
               existing_nullable=False)
    op.alter_column('courses', 'difficulty',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='coursedifficulty'),
               existing_nullable=False)
    op.alter_column('courses', 'category',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('TECHNOLOGY', 'VOCATIONAL', 'SOFT_SKILLS', 'LITERACY', name='coursecategory'),
               existing_nullable=False)
    op.create_table('mentor_profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('specialization', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='mentor_profiles_pkey'),
    sa.UniqueConstraint('user_id', name='mentor_profiles_user_id_key')
    )
    op.create_table('module_content',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('module_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('TEXT', 'VIDEO', 'AUDIO', 'INTERACTIVE', 'QUIZ', name='contenttype'), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('alt_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('captions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('transcript', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sign_language_video_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['course_modules.id'], name='module_content_module_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='module_content_pkey')
    )
    op.create_table('course_accessibility_features',
    sa.Column('course_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('feature', sa.VARCHAR(length=255), autoincrement=False, nullable=True)
    )
    op.create_table('course_modules',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('estimated_time', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='course_modules_pkey')
    )
    op.create_table('administrator_profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('permissions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='administrator_profiles_pkey'),
    sa.UniqueConstraint('user_id', name='administrator_profiles_user_id_key')
    )
    op.create_table('user_accessibility_needs',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('accessibility_need', sa.VARCHAR(length=255), autoincrement=False, nullable=True)
    )
    op.create_table('mentorship_sessions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('meeting_link', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('scheduled_at', postgresql.TIMESTAMP(timezone=True, precision=6), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('topic', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('mentee_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('mentor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.CheckConstraint("status::text = ANY (ARRAY['SCHEDULED'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying]::text[])", name='mentorship_sessions_status_check'),
    sa.PrimaryKeyConstraint('id', name='mentorship_sessions_pkey')
    )
    op.create_table('learner_profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('disability_types', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('mentorship_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='learner_profiles_pkey'),
    sa.UniqueConstraint('user_id', name='learner_profiles_user_id_key')
    )
    # ### end Alembic commands ###
